import mongoose from 'mongoose';

const buyerSchema = new mongoose.Schema({
  name: { type: String, required: true },
  phoneNumber: { type: String, required: true },
  emailAddress: { type: String, required: true },
  propertyCategory:{type:String, required:true, enum:['Commercial','Industrial','Land']},
  propertyTypeSelect: { 
    type: String,
    required: true,
    enum: ["Cafe", "Car Wash", "Factory","Healthcare","Hotel","Medical Center","Nursing Homes","Office","Pub","Restaurant","Retail","Shops","Shopping Center","Sports Facilities",'Unit',"Warehouse","Other"],
  },
  areaRequired: { 
    type: String,
    required: true,
    enum: [
      "Aireborough",
    "Baildon",
    "Bingley",
    "Bradford",
    "Brighouse",
    "Castleford",
    "Colne Valley",
    "Denby Dale",
    "Denholme",
    "Dewsbury",
    "Elland",
    "Featherstone",
    "Halifax",
    "Hebden Royd",
    "Heckmondwike",
    "Hemsworth",
    "Holmfirth",
    "Huddersfield",
    "Ilkley",
    "Keighley",
    "Knottingley",
    "Leeds",
    "Meltham",
    "Mirfield",
    "Morley",
    "Normanton",
    "Ossett",
    "Otley",
    "Pontefract",
    "Pudsey",
    "Queensbury and Shelf",
    "Ripponden",
    "Rothwell",
    "Shipley",
    "Silsden",
    "Skipton",
    "Spenborough",
    "Stanley",
    "Tadcaster",
    "Todmorden",
    "Wakefield",
    "Wetherby",
    "Wharfedale","Other",
    ],
  },
  FirstLineofAddress: { type: String, required: true },
  postcode: { type: String, required: true },
  budget: { 
    type: Number,
    required: true,
  },
  notes: { type: String },
  propertyAvailableDate: { type: Date, required: true },
  propertyStatus: { type: String, default: "active" },
  formCreatedDate: { type: Date, default: Date.now },
  subscribe: { type: Boolean, default: true },
});

const Buyer = mongoose.model('Buyer', buyerSchema);
export default Buyer;
